//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKITbyBDK_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskITEntities1 : DbContext
    {
        public AskITEntities1()
            : base("name=AskITEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_Rollen> Table_Rollen { get; set; }
        public DbSet<Table_Vergoedingen> Table_Vergoedingen { get; set; }
        public DbSet<Table_Wachtwoorden> Table_Wachtwoorden { get; set; }
        public DbSet<Table_Maanden> Table_Maanden { get; set; }
        public DbSet<Table_Scholen> Table_Scholen { get; set; }
        public DbSet<Table_Gebruikers> Table_Gebruikers { get; set; }
        public DbSet<Table_Gemeentes> Table_Gemeentes { get; set; }
    }
}
