//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKITbyBDK_v2.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table_Gebruikers
    {
        public int ID { get; set; }
        public string GebruikersID { get; set; }
        public string RolCode { get; set; }
        public string Naam { get; set; }
        public string Voornaam { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string IBAN { get; set; }
        public string Stamboeknummer { get; set; }
    }
}
