//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKITbyBDK_v2.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table_Vergoedingen
    {
        public string VergoedingCode { get; set; }
        public string VergoedingNaam { get; set; }
    }
}
